### ISSUE TITLE
Invoke a method on tap

### ISSUE THREAD

**Issue by azhararmar** [eddiekaiger/SwiftyAttributes#21]
Hi,

In some cases, I'd like to execute a method on click of label. Currently I am using the following method.

```
@objc func tapTermsLabel(gesture: UITapGestureRecognizer) {
    let text = (self.termsLabel.text)!
    var termsRange = (text as NSString).range(of: "Terms of Service")
    var privacyRange = (text as NSString).range(of: "Privacy Policy")
    if gesture.didTapAttributedTextInLabel(label: self.termsLabel, inRange: termsRange) {
        let viewController = WebViewViewController(url: APIEndPoint.get(type: "terms-of-service-\(getUserLocale())"))
        present(viewController, animated: true, completion: nil)
    } else if gesture.didTapAttributedTextInLabel(label: self.termsLabel, inRange: privacyRange) {
        let viewController = WebViewViewController(url: APIEndPoint.get(type: "privacy-policy-\(getUserLocale())"))
        present(viewController, animated: true, completion: nil)
    }
}

```
Although this works. It would be nice to have something similar integrated with the library for example

`"Terms of Service".onTap(#selector(methodName))`

Can this feature request be considered?

Thanks.

**Comment by eddiekaiger** [comment]
Hi, 

Thanks for the suggestion. However, this seems like something that's outside of the scope of this library. Attributed strings can be part of various different UI elements, so coupling a selector action to a string doesn't quite make sense, i.e. there's no way for a user to interact with an attributed string. I would recommend using libraries such as [KILabel](https://github.com/Krelborn/KILabel) or [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) to accomplish this while using *SwiftyAttributes* to build the actual attributed strings. You can also accomplish this with pure UIKit if you use a `UITextView` instead of a `UILabel`. See [here](https://stackoverflow.com/questions/2543967/how-to-intercept-click-on-link-in-uitextview).
